= Tan Yuanhong - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: AlgoBase

---

== Overview

AlgoBase is a desktop address book application used for teaching Software Engineering principles. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== About this portfolio

This project portfolio details my individual contributions to the *AlgoBase* project. It includes a summary of the enhancements and other contributions I made throughout the duration  of the project. Additionally, portions of my contribution to the User Guide and Developer Guide have also been included.

== Summary of contributions

* *Major enhancement*: Implemented the problem searching and sorting feature.

** What it does: allows the user to filter problems by combining search constraints on most fields (e.g. problem names, sources, descriptions, difficulty, etc.), allows user to save and reuse some typical search rules and allows user to sort the search result.

** Justification: To organize algorithmic questions, the first step is to find a proper subset of AlgoBase to either add to a training plan or solve the problems directly. The search feature is one of the most frequently used functionality in *AlgoBase*.

** Highlights: This is a full-stack feature all the components of *AlgoBase* from `Logic` to `Model` to `Storage` to `UI`. It requires an in-depth analysis of the overall architecture of *AlgoBase* as the original implementation of `find` in AddressBook accepts only one search constraint (i.e. the name), but in *AlgoBase* we need to support combination of arbitrary (non-zero) number of search constraints.

** Relevant pull requests:
https://github.com/AY1920S1-CS2103T-W11-1/main/pull/64[#64]
https://github.com/AY1920S1-CS2103T-W11-1/main/pull/90[#90]
https://github.com/AY1920S1-CS2103T-W11-1/main/pull/94[#94]
https://github.com/AY1920S1-CS2103T-W11-1/main/pull/107[#107]

* *Minor enhancement*:
** `rewind`

* *Code contributed*:
https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=le0tan[Funtional and Test Code]

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` (1 release) on GitHub
** Enhancements to existing features:
*** Re-implement the `help` command
** Documentation:
*** Explains how reserved words should work in *AlgoBase* (used as a reference in the development) https://github.com/AY1920S1-CS2103T-W11-1/main/pull/35[#35]
** Community:
*** PRs reviewed (with non-trivial review comments):

*** Contributed to forum discussions

*** Reported bugs and suggestions for other teams in the class

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=model]
include::../DeveloperGuide.adoc[tag=find]
include::../DeveloperGuide.adoc[tag=savefindrule]
